version: "2"
services:
    wordpress:
      image: wordpress:latest
      ports:
          - "80:80"
      depends_on:
          - db
      environment:
          WORDPRESS_DB_HOST: "db:3306"
      env_file: .env
      volumes:
          - ./data:/var/www/html
    db:
        image: mysql:latest
        env_file: .env
        volumes:
            - ./mysql-data:/var/lib/mysql

volumes:
    db-data:
        driver: local
